# Generated by Django 4.1 on 2022-08-10 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wenyan', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tongjia',
            old_name='from_word',
            new_name='after',
        ),
        migrations.RenameField(
            model_name='tongjia',
            old_name='to_word',
            new_name='before',
        ),
        migrations.AlterField(
            model_name='explanation',
            name='live_use',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='explanation',
            name='part_of_speech',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='jushi',
            field=models.CharField(max_length=7),
        ),
    ]
